version = 1
exclude_patterns = [
    "bin/**",
    "**/node_modules/",
    "js/**/*.min.js"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
    "requirements.txt",
]

[[analyzers]]
name = "javascript"
enabled = true
dependency_file_paths = [
    "./web/package.json",
]