services:
  qdrant:
    image: qdrant/qdrant:v1.2.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"

volumes:
  qdrant_storage: