services:
  qdrant:
    image: qdrant/qdrant:v1.2.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"
  server:
    working_dir: /app
    container_name: remembear-backend
    image: python:3.12.4-slim-bullseye
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    command: >
      bash -c "
        source /app/script/export_env.sh &&
        if [ ! -d /app/.venv ]; then
          python -m venv /app/.venv &&
          source /app/.venv/bin/activate &&
          pip install -r /app/requirements.txt;
        else
          pip install -r /app/requirements.txt;
          source /app/.venv/bin/activate;
        fi &&
        fastapi run server/main.py --host 0.0.0.0 &
        sleep infinity
      "

volumes:
  qdrant_storage: